### ISSUE TITLE
Compatibility with Contao 4.13

### ISSUE THREAD

**Issue by joehi** [terminal42/contao-geoip2-country#1]
This Contao extension is not compatible with Contao version 4.13.

When I try to install the extension I get the following error message:
` - terminal42/contao-geoip2-country[1.2.0, ..., 1.2.4] require php ^7.4 -> your php version (8.1.4.0) does not satisfy that requirement.`
`- terminal42/contao-geoip2-country 1.2.5 requires doctrine/dbal ^2.11 -> found doctrine/dbal[2.11.0, ..., 2.13.8] but these were not loaded, likely because it conflicts with another require.`

**Comment by Toflar** [comment]
See https://github.com/terminal42/contao-geoip2-country/pull/2

**Comment by joehi** [comment]
See also the discussion at the [contao community](https://community.contao.org/de/showthread.php?82913-GeoIP-Erweiterung-l%C3%A4sst-sich-mit-php8-nicht-installieren). With this PR I could install and use the package with contao 4.13.
