### ISSUE TITLE
Add Option to Filter Pages Too

### ISSUE THREAD

**Issue by 360fusion** [terminal42/contao-geoip2-country#3]
Is this module still maintained?

i've been looking for a way to hide a module based on the page it is on.

This would be help full as I have a module I want on every page automatically and only need to hide it from a few pages.

It would be a pain to create a new page layout just to achieve this.

I used to use a module called boxes but this is old https://github.com/markusmilkereit/contao-boxes

Having the option to select a few pages from the site structure as another option in the module itself would be really useful.

Thanks

**Comment by aschempp** [comment]
This extension filters modules based on Geo/IP targeting. I don't think that's related to what you are asking for.
